/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author luong
 */
import java.awt.Color;
import java.util.concurrent.Semaphore;
public class FinalSolution extends javax.swing.JFrame {
    Semaphore Fork1 = new Semaphore(1);
    Semaphore Fork2 = new Semaphore(1);
    Semaphore Fork3 = new Semaphore(1);
    Semaphore Fork4 = new Semaphore(1);
    Semaphore Fork5 = new Semaphore(1);
    
    
    public class EatThread extends Thread{
        String name = "";
        public EatThread(String name){
            this.name = name;
        }
        
        public void run (){
            try {
                if (this.name.equals("Per1")){
                    Fork1.acquire();
                    Fork5.acquire();
                    lblFork1.setBackground(Color.yellow);
                    lblFork5.setBackground(Color.yellow);
                    try {
                        Thread.sleep(10000);
                    } finally{
                        Fork1.release();
                        Fork5.release();
                        lblFork1.setBackground(Color.green);
                        lblFork5.setBackground(Color.green);
                               
                    } 
                }
                else if (this.name.equals("Per2")){
                    Fork1.acquire();
                    Fork2.acquire();
                    lblFork1.setBackground(Color.yellow);
                    lblFork2.setBackground(Color.yellow);
                    try {
                        Thread.sleep(10000);
                    } finally{
                        Fork1.release();
                        Fork2.release();
                        lblFork1.setBackground(Color.green);
                        lblFork2.setBackground(Color.green);
                               
                    }
                }
                
                else if (this.name.equals("Per3")){
                    Fork2.acquire();
                    Fork3.acquire();
                    lblFork2.setBackground(Color.yellow);
                    lblFork3.setBackground(Color.yellow);
                    try {
                        Thread.sleep(10000);
                    } finally{
                        Fork2.release();
                        Fork3.release();
                        lblFork1.setBackground(Color.green);
                        lblFork5.setBackground(Color.green);
                               
                    }
                }
                else if (this.name.equals("Per4")){
                    Fork3.acquire();
                    Fork4.acquire();
                    lblFork3.setBackground(Color.yellow);
                    lblFork4.setBackground(Color.yellow);
                    try {
                        Thread.sleep(10000);
                    } finally{
                        Fork3.release();
                        Fork4.release();
                        lblFork3.setBackground(Color.green);
                        lblFork4.setBackground(Color.green);
                               
                    }
                }
                else if (this.name == "Per5"){
                    Fork4.acquire();
                    Fork5.acquire();
                    lblFork4.setBackground(Color.yellow);
                    lblFork5.setBackground(Color.yellow);
                    try {
                        Thread.sleep(10000);
                    } finally{
                        Fork4.release();
                        Fork5.release();
                        lblFork4.setBackground(Color.green);
                        lblFork5.setBackground(Color.green);
                               
                    }
                }
            } catch (InterruptedException e){
                e.printStackTrace();
            }
        }
    }
    
    
    
    /**
     * Creates new form FinalSolution
     */
    public FinalSolution() {
        initComponents();
        EatThread t1 = new EatThread("Per1");
        t1.start();
        EatThread t2 = new EatThread("Per2");
        t2.start();
        EatThread t3 = new EatThread("Per3");
        t3.start();
        EatThread t4 = new EatThread("Per4");
        t4.start();
        EatThread t5 = new EatThread("Per5");
        t5.start();
    }
    
    
    

    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnPer1 = new javax.swing.JPanel();
        lblPer1 = new javax.swing.JLabel();
        pnFork1 = new javax.swing.JPanel();
        lblFork1 = new javax.swing.JLabel();
        pnPer2 = new javax.swing.JPanel();
        lblPer2 = new javax.swing.JLabel();
        prFork2 = new javax.swing.JPanel();
        lblFork2 = new javax.swing.JLabel();
        pnPer3 = new javax.swing.JPanel();
        lblPer3 = new javax.swing.JLabel();
        pnPer4 = new javax.swing.JPanel();
        lblPer4 = new javax.swing.JLabel();
        pnFork3 = new javax.swing.JPanel();
        lblFork3 = new javax.swing.JLabel();
        pnPer5 = new javax.swing.JPanel();
        lblPer5 = new javax.swing.JLabel();
        pnFork4 = new javax.swing.JPanel();
        lblFork4 = new javax.swing.JLabel();
        pnFork5 = new javax.swing.JPanel();
        lblFork5 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnPer1.setBackground(new java.awt.Color(0, 255, 0));

        lblPer1.setText("Person1");

        javax.swing.GroupLayout pnPer1Layout = new javax.swing.GroupLayout(pnPer1);
        pnPer1.setLayout(pnPer1Layout);
        pnPer1Layout.setHorizontalGroup(
            pnPer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnPer1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPer1)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        pnPer1Layout.setVerticalGroup(
            pnPer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnPer1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblPer1)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pnFork1.setBackground(new java.awt.Color(0, 255, 0));

        lblFork1.setText("Fork1");

        javax.swing.GroupLayout pnFork1Layout = new javax.swing.GroupLayout(pnFork1);
        pnFork1.setLayout(pnFork1Layout);
        pnFork1Layout.setHorizontalGroup(
            pnFork1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnFork1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFork1)
                .addContainerGap(12, Short.MAX_VALUE))
        );
        pnFork1Layout.setVerticalGroup(
            pnFork1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnFork1Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(lblFork1)
                .addContainerGap())
        );

        pnPer2.setBackground(new java.awt.Color(0, 255, 0));

        lblPer2.setText("Person2");

        javax.swing.GroupLayout pnPer2Layout = new javax.swing.GroupLayout(pnPer2);
        pnPer2.setLayout(pnPer2Layout);
        pnPer2Layout.setHorizontalGroup(
            pnPer2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnPer2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPer2)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        pnPer2Layout.setVerticalGroup(
            pnPer2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnPer2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblPer2)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        prFork2.setBackground(new java.awt.Color(0, 255, 0));

        lblFork2.setText("Fork2");

        javax.swing.GroupLayout prFork2Layout = new javax.swing.GroupLayout(prFork2);
        prFork2.setLayout(prFork2Layout);
        prFork2Layout.setHorizontalGroup(
            prFork2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(prFork2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFork2)
                .addContainerGap(12, Short.MAX_VALUE))
        );
        prFork2Layout.setVerticalGroup(
            prFork2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(prFork2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFork2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnPer3.setBackground(new java.awt.Color(0, 255, 0));

        lblPer3.setText("Person3");

        javax.swing.GroupLayout pnPer3Layout = new javax.swing.GroupLayout(pnPer3);
        pnPer3.setLayout(pnPer3Layout);
        pnPer3Layout.setHorizontalGroup(
            pnPer3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnPer3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPer3)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        pnPer3Layout.setVerticalGroup(
            pnPer3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnPer3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblPer3)
                .addGap(22, 22, 22))
        );

        pnPer4.setBackground(new java.awt.Color(0, 255, 0));

        lblPer4.setText("Person4");

        javax.swing.GroupLayout pnPer4Layout = new javax.swing.GroupLayout(pnPer4);
        pnPer4.setLayout(pnPer4Layout);
        pnPer4Layout.setHorizontalGroup(
            pnPer4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnPer4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPer4)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        pnPer4Layout.setVerticalGroup(
            pnPer4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnPer4Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(lblPer4)
                .addGap(22, 22, 22))
        );

        pnFork3.setBackground(new java.awt.Color(0, 255, 0));

        lblFork3.setText("Fork3");

        javax.swing.GroupLayout pnFork3Layout = new javax.swing.GroupLayout(pnFork3);
        pnFork3.setLayout(pnFork3Layout);
        pnFork3Layout.setHorizontalGroup(
            pnFork3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnFork3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFork3)
                .addContainerGap(12, Short.MAX_VALUE))
        );
        pnFork3Layout.setVerticalGroup(
            pnFork3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnFork3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFork3)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pnPer5.setBackground(new java.awt.Color(0, 255, 0));

        lblPer5.setText("Person5");

        javax.swing.GroupLayout pnPer5Layout = new javax.swing.GroupLayout(pnPer5);
        pnPer5.setLayout(pnPer5Layout);
        pnPer5Layout.setHorizontalGroup(
            pnPer5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnPer5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPer5)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        pnPer5Layout.setVerticalGroup(
            pnPer5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnPer5Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblPer5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnFork4.setBackground(new java.awt.Color(0, 255, 0));

        lblFork4.setText("Fork4");

        javax.swing.GroupLayout pnFork4Layout = new javax.swing.GroupLayout(pnFork4);
        pnFork4.setLayout(pnFork4Layout);
        pnFork4Layout.setHorizontalGroup(
            pnFork4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnFork4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFork4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnFork4Layout.setVerticalGroup(
            pnFork4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnFork4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFork4)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pnFork5.setBackground(new java.awt.Color(0, 255, 0));

        lblFork5.setText("Fork5");

        javax.swing.GroupLayout pnFork5Layout = new javax.swing.GroupLayout(pnFork5);
        pnFork5.setLayout(pnFork5Layout);
        pnFork5Layout.setHorizontalGroup(
            pnFork5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnFork5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFork5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnFork5Layout.setVerticalGroup(
            pnFork5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnFork5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFork5)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel11.setBackground(new java.awt.Color(255, 255, 0));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 39, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jLabel1.setText("Eating / In used");

        jPanel1.setBackground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 39, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 29, Short.MAX_VALUE)
        );

        jLabel2.setText("Hungry");

        jPanel2.setBackground(new java.awt.Color(0, 255, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 39, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 32, Short.MAX_VALUE)
        );

        jLabel3.setText("Thinking / Not In used");

        jButton1.setText("Run");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(203, 203, 203)
                        .addComponent(pnFork5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnFork3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnPer1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnPer3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pnFork1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(220, 220, 220))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(pnPer5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnPer2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(141, 141, 141))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnPer4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(406, 406, 406))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addComponent(pnFork4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(prFork2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(192, 192, 192))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(179, 179, 179))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(pnPer1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(92, 92, 92)
                                .addComponent(pnFork1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(pnFork5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pnPer5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnPer2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pnFork4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(prFork2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pnPer4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnPer3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnFork3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 25, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FinalSolution.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FinalSolution.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FinalSolution.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FinalSolution.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        
        
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FinalSolution().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblFork1;
    private javax.swing.JLabel lblFork2;
    private javax.swing.JLabel lblFork3;
    private javax.swing.JLabel lblFork4;
    private javax.swing.JLabel lblFork5;
    private javax.swing.JLabel lblPer1;
    private javax.swing.JLabel lblPer2;
    private javax.swing.JLabel lblPer3;
    private javax.swing.JLabel lblPer4;
    private javax.swing.JLabel lblPer5;
    private javax.swing.JPanel pnFork1;
    private javax.swing.JPanel pnFork3;
    private javax.swing.JPanel pnFork4;
    private javax.swing.JPanel pnFork5;
    private javax.swing.JPanel pnPer1;
    private javax.swing.JPanel pnPer2;
    private javax.swing.JPanel pnPer3;
    private javax.swing.JPanel pnPer4;
    private javax.swing.JPanel pnPer5;
    private javax.swing.JPanel prFork2;
    // End of variables declaration//GEN-END:variables
}
